#!/bin/sh

DIR=`pwd`
PORT=$1

echo [DEFAULT] > cfg/at_server.cfg
echo ConnectionType=acceptor >> cfg/at_server.cfg
echo SocketAcceptPort=$PORT >> cfg/at_server.cfg
echo StartTime=00:00:00 >> cfg/at_server.cfg
echo EndTime=00:00:00 >> cfg/at_server.cfg
echo SenderCompID=ISLD >> cfg/at_server.cfg
echo TargetCompID=TW >> cfg/at_server.cfg
echo ResetOnDisconnect=Y >> cfg/at_server.cfg
echo [SESSION] >> cfg/at_server.cfg
echo BeginString=FIX.4.0 >> cfg/at_server.cfg
echo DataDictionary=../spec/FIX40.xml >> cfg/at_server.cfg
echo [SESSION] >> cfg/at_server.cfg
echo BeginString=FIX.4.1 >> cfg/at_server.cfg
echo DataDictionary=../spec/FIX41.xml >> cfg/at_server.cfg
echo [SESSION] >> cfg/at_server.cfg
echo BeginString=FIX.4.2 >> cfg/at_server.cfg
echo DataDictionary=../spec/FIX42.xml >> cfg/at_server.cfg
echo [SESSION] >> cfg/at_server.cfg
echo BeginString=FIX.4.3 >> cfg/at_server.cfg
echo DataDictionary=../spec/FIX43.xml >> cfg/at_server.cfg

../bin/at_server -f cfg/at_server.cfg -t &
sleep 5
cd $DIR
ruby Runner.rb 127.0.0.1 $PORT definitions/server/fix*/*.def
RESULT=$?
kill $!
exit $RESULT