#!/bin/sh

export LD_LIBRARY_PATH=../src/C++/.libs
export DYLD_LIBRARY_PATH=$LD_LIBRARY_PATH
export RUBYLIB=../lib/ruby

DIR=`pwd`
PORT=$1
./setup $PORT

ruby -I ../lib/ruby ../src/at.rb cfg/at.cfg &
PROCID=$!
cd $DIR
ruby Runner.rb 127.0.0.1 $PORT definitions/server/fix*/*.def
RESULT=$?
kill $PROCID
exit $RESULT
