/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_quickfix_ThreadedSocketInitiator */

#ifndef _Included_org_quickfix_ThreadedSocketInitiator
#define _Included_org_quickfix_ThreadedSocketInitiator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_quickfix_ThreadedSocketInitiator
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_ThreadedSocketInitiator_create
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_ThreadedSocketInitiator
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_ThreadedSocketInitiator_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_ThreadedSocketInitiator
 * Method:    doStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_ThreadedSocketInitiator_doStart
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_ThreadedSocketInitiator
 * Method:    doBlock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_ThreadedSocketInitiator_doBlock
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_ThreadedSocketInitiator
 * Method:    doPoll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_ThreadedSocketInitiator_doPoll
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_ThreadedSocketInitiator
 * Method:    doStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_ThreadedSocketInitiator_doStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
