/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_quickfix_Session */

#ifndef _Included_org_quickfix_Session
#define _Included_org_quickfix_Session
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_quickfix_Session
 * Method:    sendToTarget0
 * Signature: (Lorg/quickfix/Message;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_quickfix_Session_sendToTarget0__Lorg_quickfix_Message_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_quickfix_Session
 * Method:    sendToTarget0
 * Signature: (Lorg/quickfix/Message;Lorg/quickfix/SessionID;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_quickfix_Session_sendToTarget0__Lorg_quickfix_Message_2Lorg_quickfix_SessionID_2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_quickfix_Session
 * Method:    sendToTarget0
 * Signature: (Lorg/quickfix/Message;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_quickfix_Session_sendToTarget0__Lorg_quickfix_Message_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
