/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_quickfix_FileLogFactory */

#ifndef _Included_org_quickfix_FileLogFactory
#define _Included_org_quickfix_FileLogFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_quickfix_FileLogFactory
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_FileLogFactory_create__
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_FileLogFactory
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_FileLogFactory_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_FileLogFactory
 * Method:    create
 * Signature: (Lorg/quickfix/SessionID;)Lorg/quickfix/Log;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_FileLogFactory_create__Lorg_quickfix_SessionID_2
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
