/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_quickfix_Group */

#ifndef _Included_org_quickfix_Group
#define _Included_org_quickfix_Group
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_quickfix_Group
 * Method:    create
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Group_create__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_quickfix_Group
 * Method:    create
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Group_create__II_3I
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     org_quickfix_Group
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Group_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_Group
 * Method:    addGroup0
 * Signature: (Lorg/quickfix/Group;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Group_addGroup0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_quickfix_Group
 * Method:    getGroup0
 * Signature: (ILorg/quickfix/Group;)Lorg/quickfix/Group;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_Group_getGroup0
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_quickfix_Group
 * Method:    setString0
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Group_setString0
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_quickfix_Group
 * Method:    setBoolean0
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Group_setBoolean0
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_quickfix_Group
 * Method:    setChar0
 * Signature: (IC)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Group_setChar0
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     org_quickfix_Group
 * Method:    setInt0
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Group_setInt0
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_quickfix_Group
 * Method:    setDouble0
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Group_setDouble0
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_quickfix_Group
 * Method:    setUtcTimeStamp0
 * Signature: (ILjava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Group_setUtcTimeStamp0
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_quickfix_Group
 * Method:    setUtcTimeOnly0
 * Signature: (ILjava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Group_setUtcTimeOnly0
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_quickfix_Group
 * Method:    setUtcDate0
 * Signature: (ILjava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Group_setUtcDate0
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_quickfix_Group
 * Method:    getString0
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_quickfix_Group_getString0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Group
 * Method:    getBoolean0
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_quickfix_Group_getBoolean0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Group
 * Method:    getChar0
 * Signature: (I)C
 */
JNIEXPORT jchar JNICALL Java_org_quickfix_Group_getChar0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Group
 * Method:    getInt0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_quickfix_Group_getInt0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Group
 * Method:    getDouble0
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_quickfix_Group_getDouble0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Group
 * Method:    getUtcTimeStamp0
 * Signature: (I)Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_Group_getUtcTimeStamp0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Group
 * Method:    getUtcTimeOnly0
 * Signature: (I)Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_Group_getUtcTimeOnly0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Group
 * Method:    getUtcDate0
 * Signature: (I)Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_Group_getUtcDate0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Group
 * Method:    isSetField0
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_quickfix_Group_isSetField0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Group
 * Method:    toString0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_quickfix_Group_toString0
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_Group
 * Method:    fromString0
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Group_fromString0
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
