/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_quickfix_Message */

#ifndef _Included_org_quickfix_Message
#define _Included_org_quickfix_Message
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_quickfix_Message
 * Method:    InitializeXML
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_quickfix_Message_InitializeXML
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_quickfix_Message
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_create
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_Message
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_Message
 * Method:    clone
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_Message_clone
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_Message
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_quickfix_Message_toString
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_Message
 * Method:    toXML
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_quickfix_Message_toXML
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_Message
 * Method:    fromString
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_fromString
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_quickfix_Message
 * Method:    addGroup0
 * Signature: (Lorg/quickfix/Group;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_addGroup0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_quickfix_Message
 * Method:    getGroup0
 * Signature: (ILorg/quickfix/Group;)Lorg/quickfix/Group;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_Message_getGroup0
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_quickfix_Message
 * Method:    setString0
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setString0
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_quickfix_Message
 * Method:    setBoolean0
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setBoolean0
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_quickfix_Message
 * Method:    setChar0
 * Signature: (IC)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setChar0
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     org_quickfix_Message
 * Method:    setInt0
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setInt0
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    setDouble0
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setDouble0
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_quickfix_Message
 * Method:    setUtcTimeStamp0
 * Signature: (ILjava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setUtcTimeStamp0
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_quickfix_Message
 * Method:    setUtcTimeOnly0
 * Signature: (ILjava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setUtcTimeOnly0
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_quickfix_Message
 * Method:    setUtcDate0
 * Signature: (ILjava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setUtcDate0
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_quickfix_Message
 * Method:    getString0
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_quickfix_Message_getString0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getBoolean0
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_quickfix_Message_getBoolean0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getChar0
 * Signature: (I)C
 */
JNIEXPORT jchar JNICALL Java_org_quickfix_Message_getChar0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getInt0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_quickfix_Message_getInt0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getDouble0
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_quickfix_Message_getDouble0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getUtcTimeStamp0
 * Signature: (I)Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_Message_getUtcTimeStamp0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getUtcTimeOnly0
 * Signature: (I)Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_Message_getUtcTimeOnly0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getUtcDate0
 * Signature: (I)Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_Message_getUtcDate0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    setHeaderString0
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setHeaderString0
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_quickfix_Message
 * Method:    setHeaderBoolean0
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setHeaderBoolean0
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_quickfix_Message
 * Method:    setHeaderChar0
 * Signature: (IC)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setHeaderChar0
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     org_quickfix_Message
 * Method:    setHeaderInt0
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setHeaderInt0
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    setHeaderDouble0
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setHeaderDouble0
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_quickfix_Message
 * Method:    setHeaderUtcTimeStamp0
 * Signature: (ILjava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setHeaderUtcTimeStamp0
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_quickfix_Message
 * Method:    setHeaderUtcTimeOnly0
 * Signature: (ILjava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setHeaderUtcTimeOnly0
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_quickfix_Message
 * Method:    setHeaderUtcDate0
 * Signature: (ILjava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setHeaderUtcDate0
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_quickfix_Message
 * Method:    getHeaderString0
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_quickfix_Message_getHeaderString0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getHeaderBoolean0
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_quickfix_Message_getHeaderBoolean0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getHeaderChar0
 * Signature: (I)C
 */
JNIEXPORT jchar JNICALL Java_org_quickfix_Message_getHeaderChar0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getHeaderInt0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_quickfix_Message_getHeaderInt0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getHeaderDouble0
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_quickfix_Message_getHeaderDouble0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getHeaderUtcTimeStamp0
 * Signature: (I)Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_Message_getHeaderUtcTimeStamp0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getHeaderUtcTimeOnly0
 * Signature: (I)Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_Message_getHeaderUtcTimeOnly0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getHeaderUtcDate0
 * Signature: (I)Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_Message_getHeaderUtcDate0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    setTrailerString0
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setTrailerString0
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_quickfix_Message
 * Method:    setTrailerBoolean0
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setTrailerBoolean0
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_quickfix_Message
 * Method:    setTrailerChar0
 * Signature: (IC)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setTrailerChar0
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     org_quickfix_Message
 * Method:    setTrailerInt0
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setTrailerInt0
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    setTrailerDouble0
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setTrailerDouble0
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_quickfix_Message
 * Method:    setTrailerUtcTimeStamp0
 * Signature: (ILjava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setTrailerUtcTimeStamp0
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_quickfix_Message
 * Method:    setTrailerUtcTimeOnly0
 * Signature: (ILjava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setTrailerUtcTimeOnly0
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_quickfix_Message
 * Method:    setTrailerUtcDate0
 * Signature: (ILjava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Message_setTrailerUtcDate0
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_quickfix_Message
 * Method:    getTrailerString0
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_quickfix_Message_getTrailerString0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getTrailerBoolean0
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_quickfix_Message_getTrailerBoolean0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getTrailerChar0
 * Signature: (I)C
 */
JNIEXPORT jchar JNICALL Java_org_quickfix_Message_getTrailerChar0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getTrailerInt0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_quickfix_Message_getTrailerInt0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getTrailerDouble0
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_quickfix_Message_getTrailerDouble0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getTrailerUtcTimeStamp0
 * Signature: (I)Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_Message_getTrailerUtcTimeStamp0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getTrailerUtcTimeOnly0
 * Signature: (I)Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_Message_getTrailerUtcTimeOnly0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Message
 * Method:    getTrailerUtcDate0
 * Signature: (I)Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_Message_getTrailerUtcDate0
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
