/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_quickfix_MySQLLogFactory */

#ifndef _Included_org_quickfix_MySQLLogFactory
#define _Included_org_quickfix_MySQLLogFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_quickfix_MySQLLogFactory
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_MySQLLogFactory_create__
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_MySQLLogFactory
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_MySQLLogFactory_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_MySQLLogFactory
 * Method:    create
 * Signature: (Lorg/quickfix/SessionID;)Lorg/quickfix/Log;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_MySQLLogFactory_create__Lorg_quickfix_SessionID_2
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
