/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_quickfix_SessionSettings */

#ifndef _Included_org_quickfix_SessionSettings
#define _Included_org_quickfix_SessionSettings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_quickfix_SessionSettings
 * Method:    create
 * Signature: (Ljava/io/InputStream;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_SessionSettings_create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_quickfix_SessionSettings
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_SessionSettings_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_SessionSettings
 * Method:    getString
 * Signature: (Lorg/quickfix/SessionID;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_quickfix_SessionSettings_getString
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     org_quickfix_SessionSettings
 * Method:    getLong
 * Signature: (Lorg/quickfix/SessionID;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_quickfix_SessionSettings_getLong
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     org_quickfix_SessionSettings
 * Method:    getDouble
 * Signature: (Lorg/quickfix/SessionID;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_org_quickfix_SessionSettings_getDouble
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     org_quickfix_SessionSettings
 * Method:    getBool
 * Signature: (Lorg/quickfix/SessionID;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_quickfix_SessionSettings_getBool
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     org_quickfix_SessionSettings
 * Method:    setString
 * Signature: (Lorg/quickfix/SessionID;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_SessionSettings_setString
  (JNIEnv *, jobject, jobject, jstring, jstring);

/*
 * Class:     org_quickfix_SessionSettings
 * Method:    setLong
 * Signature: (Lorg/quickfix/SessionID;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_SessionSettings_setLong
  (JNIEnv *, jobject, jobject, jstring, jlong);

/*
 * Class:     org_quickfix_SessionSettings
 * Method:    setDouble
 * Signature: (Lorg/quickfix/SessionID;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_SessionSettings_setDouble
  (JNIEnv *, jobject, jobject, jstring, jdouble);

/*
 * Class:     org_quickfix_SessionSettings
 * Method:    setBool
 * Signature: (Lorg/quickfix/SessionID;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_SessionSettings_setBool
  (JNIEnv *, jobject, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
