/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_quickfix_ScreenLogFactory */

#ifndef _Included_org_quickfix_ScreenLogFactory
#define _Included_org_quickfix_ScreenLogFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_quickfix_ScreenLogFactory
 * Method:    create
 * Signature: (ZZZ)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_ScreenLogFactory_create__ZZZ
  (JNIEnv *, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     org_quickfix_ScreenLogFactory
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_ScreenLogFactory_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_ScreenLogFactory
 * Method:    create
 * Signature: (Lorg/quickfix/SessionID;)Lorg/quickfix/Log;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_ScreenLogFactory_create__Lorg_quickfix_SessionID_2
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
