/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_quickfix_Settings */

#ifndef _Included_org_quickfix_Settings
#define _Included_org_quickfix_Settings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_quickfix_Settings
 * Method:    create
 * Signature: (Ljava/io/InputStream;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Settings_create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_quickfix_Settings
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Settings_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
