/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_quickfix_SocketAcceptor */

#ifndef _Included_org_quickfix_SocketAcceptor
#define _Included_org_quickfix_SocketAcceptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_quickfix_SocketAcceptor
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_SocketAcceptor_create
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_SocketAcceptor
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_SocketAcceptor_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_SocketAcceptor
 * Method:    doStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_SocketAcceptor_doStart
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_SocketAcceptor
 * Method:    doBlock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_SocketAcceptor_doBlock
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_SocketAcceptor
 * Method:    doPoll
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_quickfix_SocketAcceptor_doPoll
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_SocketAcceptor
 * Method:    doStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_SocketAcceptor_doStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
