/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_quickfix_MySQLStore */

#ifndef _Included_org_quickfix_MySQLStore
#define _Included_org_quickfix_MySQLStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_quickfix_MySQLStore
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_MySQLStore_create
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_MySQLStore
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_MySQLStore_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_MySQLStore
 * Method:    set0
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_quickfix_MySQLStore_set0
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_quickfix_MySQLStore
 * Method:    get0
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_quickfix_MySQLStore_get0__ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_quickfix_MySQLStore
 * Method:    get0
 * Signature: (IILjava/util/Collection;)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_MySQLStore_get0__IILjava_util_Collection_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     org_quickfix_MySQLStore
 * Method:    getNextSenderMsgSeqNum0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_quickfix_MySQLStore_getNextSenderMsgSeqNum0
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_MySQLStore
 * Method:    getNextTargetMsgSeqNum0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_quickfix_MySQLStore_getNextTargetMsgSeqNum0
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_MySQLStore
 * Method:    setNextSenderMsgSeqNum0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_MySQLStore_setNextSenderMsgSeqNum0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_MySQLStore
 * Method:    setNextTargetMsgSeqNum0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_MySQLStore_setNextTargetMsgSeqNum0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_MySQLStore
 * Method:    incrNextSenderMsgSeqNum0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_MySQLStore_incrNextSenderMsgSeqNum0
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_MySQLStore
 * Method:    incrNextTargetMsgSeqNum0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_MySQLStore_incrNextTargetMsgSeqNum0
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_MySQLStore
 * Method:    getCreationTime0
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_MySQLStore_getCreationTime0
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_MySQLStore
 * Method:    reset0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_MySQLStore_reset0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
