/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_quickfix_Session */

#ifndef _Included_org_quickfix_Session
#define _Included_org_quickfix_Session
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_quickfix_Session
 * Method:    sendToTarget
 * Signature: (Lorg/quickfix/Message;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_quickfix_Session_sendToTarget__Lorg_quickfix_Message_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_quickfix_Session
 * Method:    sendToTarget
 * Signature: (Lorg/quickfix/Message;Lorg/quickfix/SessionID;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_quickfix_Session_sendToTarget__Lorg_quickfix_Message_2Lorg_quickfix_SessionID_2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_quickfix_Session
 * Method:    sendToTarget
 * Signature: (Lorg/quickfix/Message;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_quickfix_Session_sendToTarget__Lorg_quickfix_Message_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     org_quickfix_Session
 * Method:    lookupSession
 * Signature: (Lorg/quickfix/SessionID;)Lorg/quickfix/Session;
 */
JNIEXPORT jobject JNICALL Java_org_quickfix_Session_lookupSession
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_quickfix_Session
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Session_reset
  (JNIEnv *, jobject);

/*
 * Class:     org_quickfix_Session
 * Method:    setNextSenderMsgSeqNum
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Session_setNextSenderMsgSeqNum
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_quickfix_Session
 * Method:    setNextTargetMsgSeqNum
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_quickfix_Session_setNextTargetMsgSeqNum
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
