/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_SocketAcceptor */

#ifndef _Included_quickfix_SocketAcceptor
#define _Included_quickfix_SocketAcceptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_SocketAcceptor
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketAcceptor_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketAcceptor
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketAcceptor_destroy
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketAcceptor
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketAcceptor_start
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketAcceptor
 * Method:    block
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketAcceptor_block
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketAcceptor
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketAcceptor_stop__
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketAcceptor
 * Method:    stop
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketAcceptor_stop__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     quickfix_SocketAcceptor
 * Method:    isLoggedOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_SocketAcceptor_isLoggedOn
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketAcceptor
 * Method:    getSessions
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_quickfix_SocketAcceptor_getSessions
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
