/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_ScreenLog */

#ifndef _Included_quickfix_ScreenLog
#define _Included_quickfix_ScreenLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_ScreenLog
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_ScreenLog_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_ScreenLog
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_ScreenLog_destroy
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_ScreenLog
 * Method:    onIncoming0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_quickfix_ScreenLog_onIncoming0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     quickfix_ScreenLog
 * Method:    onOutgoing0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_quickfix_ScreenLog_onOutgoing0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     quickfix_ScreenLog
 * Method:    onEvent0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_quickfix_ScreenLog_onEvent0
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
