/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_ThreadedSocketAcceptor */

#ifndef _Included_quickfix_ThreadedSocketAcceptor
#define _Included_quickfix_ThreadedSocketAcceptor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
