/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_Group_Iterator */

#ifndef _Included_quickfix_Group_Iterator
#define _Included_quickfix_Group_Iterator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
