/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_MemoryStore */

#ifndef _Included_quickfix_MemoryStore
#define _Included_quickfix_MemoryStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_MemoryStore
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_MemoryStore_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_MemoryStore
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_MemoryStore_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
