/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_ThreadedSocketAcceptor */

#ifndef _Included_quickfix_ThreadedSocketAcceptor
#define _Included_quickfix_ThreadedSocketAcceptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_ThreadedSocketAcceptor
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_ThreadedSocketAcceptor_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_ThreadedSocketAcceptor
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_ThreadedSocketAcceptor_destroy
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_ThreadedSocketAcceptor
 * Method:    doStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_ThreadedSocketAcceptor_doStart
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_ThreadedSocketAcceptor
 * Method:    doBlock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_ThreadedSocketAcceptor_doBlock
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_ThreadedSocketAcceptor
 * Method:    doPoll
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_ThreadedSocketAcceptor_doPoll
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_ThreadedSocketAcceptor
 * Method:    doStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_ThreadedSocketAcceptor_doStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
