/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_FileLog */

#ifndef _Included_quickfix_FileLog
#define _Included_quickfix_FileLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_FileLog
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_FileLog_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_FileLog
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_FileLog_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
