/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_MSSQLLog */

#ifndef _Included_quickfix_MSSQLLog
#define _Included_quickfix_MSSQLLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_MSSQLLog
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_MSSQLLog_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_MSSQLLog
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_MSSQLLog_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
