/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_MySQLStore */

#ifndef _Included_quickfix_MySQLStore
#define _Included_quickfix_MySQLStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_MySQLStore
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_MySQLStore_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_MySQLStore
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_MySQLStore_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
