/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_SocketAcceptor */

#ifndef _Included_quickfix_SocketAcceptor
#define _Included_quickfix_SocketAcceptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_SocketAcceptor
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketAcceptor_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketAcceptor
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketAcceptor_destroy
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketAcceptor
 * Method:    doStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketAcceptor_doStart
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketAcceptor
 * Method:    doBlock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketAcceptor_doBlock
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketAcceptor
 * Method:    doPoll
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_SocketAcceptor_doPoll
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketAcceptor
 * Method:    doStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketAcceptor_doStop__
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketAcceptor
 * Method:    doStop
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketAcceptor_doStop__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     quickfix_SocketAcceptor
 * Method:    doIsLoggedOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_SocketAcceptor_doIsLoggedOn
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketAcceptor
 * Method:    doGetSessions
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_quickfix_SocketAcceptor_doGetSessions
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
