/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_OdbcStore */

#ifndef _Included_quickfix_OdbcStore
#define _Included_quickfix_OdbcStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_OdbcStore
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_OdbcStore_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_OdbcStore
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_OdbcStore_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
