/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_PostgreSQLStoreFactory */

#ifndef _Included_quickfix_PostgreSQLStoreFactory
#define _Included_quickfix_PostgreSQLStoreFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_PostgreSQLStoreFactory
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_PostgreSQLStoreFactory_create__
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_PostgreSQLStoreFactory
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_PostgreSQLStoreFactory_destroy
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_PostgreSQLStoreFactory
 * Method:    create
 * Signature: (Lquickfix/SessionID;)Lquickfix/MessageStore;
 */
JNIEXPORT jobject JNICALL Java_quickfix_PostgreSQLStoreFactory_create__Lquickfix_SessionID_2
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
