/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_MSSQLLogFactory */

#ifndef _Included_quickfix_MSSQLLogFactory
#define _Included_quickfix_MSSQLLogFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_MSSQLLogFactory
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_MSSQLLogFactory_create__
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_MSSQLLogFactory
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_MSSQLLogFactory_destroy
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_MSSQLLogFactory
 * Method:    create
 * Signature: (Lquickfix/SessionID;)Lquickfix/Log;
 */
JNIEXPORT jobject JNICALL Java_quickfix_MSSQLLogFactory_create__Lquickfix_SessionID_2
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
