/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_FileStore */

#ifndef _Included_quickfix_FileStore
#define _Included_quickfix_FileStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_FileStore
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_FileStore_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_FileStore
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_FileStore_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
