/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_DataDictionary */

#ifndef _Included_quickfix_DataDictionary
#define _Included_quickfix_DataDictionary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_DataDictionary
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_DataDictionary_create__
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_DataDictionary
 * Method:    create
 * Signature: (Lquickfix/DataDictionary;)V
 */
JNIEXPORT void JNICALL Java_quickfix_DataDictionary_create__Lquickfix_DataDictionary_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     quickfix_DataDictionary
 * Method:    create
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_quickfix_DataDictionary_create__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     quickfix_DataDictionary
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_DataDictionary_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
