/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_Session */

#ifndef _Included_quickfix_Session
#define _Included_quickfix_Session
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_Session
 * Method:    sendToTarget
 * Signature: (Lquickfix/Message;)Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_Session_sendToTarget__Lquickfix_Message_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     quickfix_Session
 * Method:    sendToTarget
 * Signature: (Lquickfix/Message;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_Session_sendToTarget__Lquickfix_Message_2Ljava_lang_String_2
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     quickfix_Session
 * Method:    sendToTarget
 * Signature: (Lquickfix/Message;Lquickfix/SessionID;)Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_Session_sendToTarget__Lquickfix_Message_2Lquickfix_SessionID_2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     quickfix_Session
 * Method:    sendToTarget
 * Signature: (Lquickfix/Message;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_Session_sendToTarget__Lquickfix_Message_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     quickfix_Session
 * Method:    sendToTarget
 * Signature: (Lquickfix/Message;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_Session_sendToTarget__Lquickfix_Message_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring);

/*
 * Class:     quickfix_Session
 * Method:    lookupSession
 * Signature: (Lquickfix/SessionID;)Lquickfix/Session;
 */
JNIEXPORT jobject JNICALL Java_quickfix_Session_lookupSession
  (JNIEnv *, jclass, jobject);

/*
 * Class:     quickfix_Session
 * Method:    logon
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_Session_logon
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_Session
 * Method:    logout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_Session_logout
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_Session
 * Method:    isEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_Session_isEnabled
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_Session
 * Method:    sentLogon
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_Session_sentLogon
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_Session
 * Method:    sentLogout
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_Session_sentLogout
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_Session
 * Method:    receivedLogon
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_Session_receivedLogon
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_Session
 * Method:    isLoggedOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_Session_isLoggedOn
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_Session
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_Session_reset
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_Session
 * Method:    setNextSenderMsgSeqNum
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_quickfix_Session_setNextSenderMsgSeqNum
  (JNIEnv *, jobject, jint);

/*
 * Class:     quickfix_Session
 * Method:    setNextTargetMsgSeqNum
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_quickfix_Session_setNextTargetMsgSeqNum
  (JNIEnv *, jobject, jint);

/*
 * Class:     quickfix_Session
 * Method:    getExpectedSenderNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_quickfix_Session_getExpectedSenderNum
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_Session
 * Method:    getExpectedTargetNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_quickfix_Session_getExpectedTargetNum
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_Session
 * Method:    getLog
 * Signature: ()Lquickfix/Log;
 */
JNIEXPORT jobject JNICALL Java_quickfix_Session_getLog
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_Session
 * Method:    getStore
 * Signature: ()Lquickfix/MessageStore;
 */
JNIEXPORT jobject JNICALL Java_quickfix_Session_getStore
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
