/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_SessionID */

#ifndef _Included_quickfix_SessionID
#define _Included_quickfix_SessionID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_SessionID
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_quickfix_SessionID_create
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     quickfix_SessionID
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_SessionID_destroy
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SessionID
 * Method:    getBeginString0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_quickfix_SessionID_getBeginString0
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SessionID
 * Method:    getSenderCompID0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_quickfix_SessionID_getSenderCompID0
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SessionID
 * Method:    getTargetCompID0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_quickfix_SessionID_getTargetCompID0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
