/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_ScreenLogFactory */

#ifndef _Included_quickfix_ScreenLogFactory
#define _Included_quickfix_ScreenLogFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_ScreenLogFactory
 * Method:    _create
 * Signature: (Lquickfix/SessionSettings;)V
 */
JNIEXPORT void JNICALL Java_quickfix_ScreenLogFactory__1create__Lquickfix_SessionSettings_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     quickfix_ScreenLogFactory
 * Method:    _create
 * Signature: (ZZZ)V
 */
JNIEXPORT void JNICALL Java_quickfix_ScreenLogFactory__1create__ZZZ
  (JNIEnv *, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     quickfix_ScreenLogFactory
 * Method:    _destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_ScreenLogFactory__1destroy
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_ScreenLogFactory
 * Method:    create
 * Signature: ()Lquickfix/Log;
 */
JNIEXPORT jobject JNICALL Java_quickfix_ScreenLogFactory_create__
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_ScreenLogFactory
 * Method:    create
 * Signature: (Lquickfix/SessionID;)Lquickfix/Log;
 */
JNIEXPORT jobject JNICALL Java_quickfix_ScreenLogFactory_create__Lquickfix_SessionID_2
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
