/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_MemoryStore */

#ifndef _Included_quickfix_MemoryStore
#define _Included_quickfix_MemoryStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_MemoryStore
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_MemoryStore_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_MemoryStore
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_MemoryStore_destroy
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_MemoryStore
 * Method:    set0
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_MemoryStore_set0
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     quickfix_MemoryStore
 * Method:    get0
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_MemoryStore_get0__ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     quickfix_MemoryStore
 * Method:    get0
 * Signature: (IILjava/util/Collection;)V
 */
JNIEXPORT void JNICALL Java_quickfix_MemoryStore_get0__IILjava_util_Collection_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     quickfix_MemoryStore
 * Method:    getNextSenderMsgSeqNum0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_quickfix_MemoryStore_getNextSenderMsgSeqNum0
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_MemoryStore
 * Method:    getNextTargetMsgSeqNum0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_quickfix_MemoryStore_getNextTargetMsgSeqNum0
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_MemoryStore
 * Method:    setNextSenderMsgSeqNum0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_quickfix_MemoryStore_setNextSenderMsgSeqNum0
  (JNIEnv *, jobject, jint);

/*
 * Class:     quickfix_MemoryStore
 * Method:    setNextTargetMsgSeqNum0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_quickfix_MemoryStore_setNextTargetMsgSeqNum0
  (JNIEnv *, jobject, jint);

/*
 * Class:     quickfix_MemoryStore
 * Method:    incrNextSenderMsgSeqNum0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_MemoryStore_incrNextSenderMsgSeqNum0
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_MemoryStore
 * Method:    incrNextTargetMsgSeqNum0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_MemoryStore_incrNextTargetMsgSeqNum0
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_MemoryStore
 * Method:    getCreationTime0
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_quickfix_MemoryStore_getCreationTime0
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_MemoryStore
 * Method:    reset0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_MemoryStore_reset0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
