/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_OdbcLog */

#ifndef _Included_quickfix_OdbcLog
#define _Included_quickfix_OdbcLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_OdbcLog
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_OdbcLog_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_OdbcLog
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_OdbcLog_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
