/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_PostgreSQLLogFactory */

#ifndef _Included_quickfix_PostgreSQLLogFactory
#define _Included_quickfix_PostgreSQLLogFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_PostgreSQLLogFactory
 * Method:    _create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_PostgreSQLLogFactory__1create
  (JNIEnv *, jobject);
/*
 * Class:     quickfix_PostgreSQLLogFactory
 * Method:    _destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_PostgreSQLLogFactory__1destroy
  (JNIEnv *, jobject);
/*
 * Class:     quickfix_PostgreSQLLogFactory
 * Method:    create
 * Signature: ()Lquickfix/Log;
 */
JNIEXPORT jobject JNICALL Java_quickfix_PostgreSQLLogFactory_create__
  (JNIEnv *, jobject);
/*
 * Class:     quickfix_PostgreSQLLogFactory
 * Method:    create
 * Signature: (Lquickfix/SessionID;)Lquickfix/Log;
 */
JNIEXPORT jobject JNICALL Java_quickfix_PostgreSQLLogFactory_create__Lquickfix_SessionID_2
  (JNIEnv *, jobject, jobject);
#ifdef __cplusplus
}
#endif
#endif
