/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_SocketInitiator */

#ifndef _Included_quickfix_SocketInitiator
#define _Included_quickfix_SocketInitiator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_SocketInitiator
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketInitiator_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketInitiator
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketInitiator_destroy
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketInitiator
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketInitiator_start
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketInitiator
 * Method:    block
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketInitiator_block
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketInitiator
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketInitiator_stop__
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketInitiator
 * Method:    stop
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_quickfix_SocketInitiator_stop__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     quickfix_SocketInitiator
 * Method:    isLoggedOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_SocketInitiator_isLoggedOn
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SocketInitiator
 * Method:    getSessions
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_quickfix_SocketInitiator_getSessions
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
