/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_MSSQLStore */

#ifndef _Included_quickfix_MSSQLStore
#define _Included_quickfix_MSSQLStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_MSSQLStore
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_MSSQLStore_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_MSSQLStore
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_MSSQLStore_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
