/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_SessionID */

#ifndef _Included_quickfix_SessionID
#define _Included_quickfix_SessionID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_SessionID
 * Method:    getBeginString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_quickfix_SessionID_getBeginString
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SessionID
 * Method:    getSenderCompID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_quickfix_SessionID_getSenderCompID
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SessionID
 * Method:    getTargetCompID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_quickfix_SessionID_getTargetCompID
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SessionID
 * Method:    getSessionQualifier
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_quickfix_SessionID_getSessionQualifier
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SessionID
 * Method:    equals
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_SessionID_equals
  (JNIEnv *, jobject, jobject);

/*
 * Class:     quickfix_SessionID
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_quickfix_SessionID_toString
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_SessionID
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_quickfix_SessionID_create
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     quickfix_SessionID
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_SessionID_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
