/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_Message_Header */

#ifndef _Included_quickfix_Message_Header
#define _Included_quickfix_Message_Header
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
