/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_PostgreSQLStore */

#ifndef _Included_quickfix_PostgreSQLStore
#define _Included_quickfix_PostgreSQLStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_PostgreSQLStore
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_PostgreSQLStore_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_PostgreSQLStore
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_PostgreSQLStore_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
