/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_CppMessageStore */

#ifndef _Included_quickfix_CppMessageStore
#define _Included_quickfix_CppMessageStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_CppMessageStore
 * Method:    set
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_CppMessageStore_set
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     quickfix_CppMessageStore
 * Method:    get
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_CppMessageStore_get__ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     quickfix_CppMessageStore
 * Method:    get
 * Signature: (IILjava/util/Collection;)V
 */
JNIEXPORT void JNICALL Java_quickfix_CppMessageStore_get__IILjava_util_Collection_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     quickfix_CppMessageStore
 * Method:    getNextSenderMsgSeqNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_quickfix_CppMessageStore_getNextSenderMsgSeqNum
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_CppMessageStore
 * Method:    getNextTargetMsgSeqNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_quickfix_CppMessageStore_getNextTargetMsgSeqNum
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_CppMessageStore
 * Method:    setNextSenderMsgSeqNum
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_quickfix_CppMessageStore_setNextSenderMsgSeqNum
  (JNIEnv *, jobject, jint);

/*
 * Class:     quickfix_CppMessageStore
 * Method:    setNextTargetMsgSeqNum
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_quickfix_CppMessageStore_setNextTargetMsgSeqNum
  (JNIEnv *, jobject, jint);

/*
 * Class:     quickfix_CppMessageStore
 * Method:    incrNextSenderMsgSeqNum
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_CppMessageStore_incrNextSenderMsgSeqNum
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_CppMessageStore
 * Method:    incrNextTargetMsgSeqNum
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_CppMessageStore_incrNextTargetMsgSeqNum
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_CppMessageStore
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_CppMessageStore_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_CppMessageStore
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_CppMessageStore_destroy
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_CppMessageStore
 * Method:    getCreationTime0
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_quickfix_CppMessageStore_getCreationTime0
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_CppMessageStore
 * Method:    reset0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_CppMessageStore_reset0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
