/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_Dictionary */

#ifndef _Included_quickfix_Dictionary
#define _Included_quickfix_Dictionary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_Dictionary
 * Method:    create
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_quickfix_Dictionary_create__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     quickfix_Dictionary
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_Dictionary_create__
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_Dictionary
 * Method:    create
 * Signature: (Lquickfix/Dictionary;)V
 */
JNIEXPORT void JNICALL Java_quickfix_Dictionary_create__Lquickfix_Dictionary_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     quickfix_Dictionary
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_Dictionary_destroy
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_Dictionary
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_quickfix_Dictionary_getName
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_Dictionary
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_quickfix_Dictionary_size
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_Dictionary
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_quickfix_Dictionary_getString__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     quickfix_Dictionary
 * Method:    getString
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_quickfix_Dictionary_getString__Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     quickfix_Dictionary
 * Method:    getLong
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_quickfix_Dictionary_getLong
  (JNIEnv *, jobject, jstring);

/*
 * Class:     quickfix_Dictionary
 * Method:    getDouble
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_quickfix_Dictionary_getDouble
  (JNIEnv *, jobject, jstring);

/*
 * Class:     quickfix_Dictionary
 * Method:    getBool
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_Dictionary_getBool
  (JNIEnv *, jobject, jstring);

/*
 * Class:     quickfix_Dictionary
 * Method:    getDay
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_quickfix_Dictionary_getDay
  (JNIEnv *, jobject, jstring);

/*
 * Class:     quickfix_Dictionary
 * Method:    setString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_quickfix_Dictionary_setString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     quickfix_Dictionary
 * Method:    setLong
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_quickfix_Dictionary_setLong
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     quickfix_Dictionary
 * Method:    setDouble
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_quickfix_Dictionary_setDouble
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     quickfix_Dictionary
 * Method:    setBool
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_quickfix_Dictionary_setBool
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     quickfix_Dictionary
 * Method:    has
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_quickfix_Dictionary_has
  (JNIEnv *, jobject, jstring);

/*
 * Class:     quickfix_Dictionary
 * Method:    merge
 * Signature: (Lquickfix/Dictionary;)V
 */
JNIEXPORT void JNICALL Java_quickfix_Dictionary_merge
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
