/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_MySQLLog */

#ifndef _Included_quickfix_MySQLLog
#define _Included_quickfix_MySQLLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_MySQLLog
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_MySQLLog_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_MySQLLog
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_MySQLLog_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
