/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_ThreadedSocketInitiator */

#ifndef _Included_quickfix_ThreadedSocketInitiator
#define _Included_quickfix_ThreadedSocketInitiator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
