/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quickfix_PostgreSQLLog */

#ifndef _Included_quickfix_PostgreSQLLog
#define _Included_quickfix_PostgreSQLLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quickfix_PostgreSQLLog
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_PostgreSQLLog_create
  (JNIEnv *, jobject);

/*
 * Class:     quickfix_PostgreSQLLog
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quickfix_PostgreSQLLog_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
