xsltproc -o ..\src\C++\FixFieldNumbers.h FieldNumbers.xsl FIX50.xml 
xsltproc -o ..\src\C++\FixTFieldNumbers.h FieldNumbers.xsl FIXT11.xml 
xsltproc -o ..\src\C++\FixFields.h Fields.xsl FIX50.xml 
xsltproc -o ..\src\C++\FixTFields.h Fields.xsl FIXT11.xml 
xsltproc -o ..\src\C++\FixValues.h Values.xsl FIX50.xml 
xsltproc -o ..\src\C++\FixTValues.h Values.xsl FIXT11.xml 
xsltproc -o ..\src\C++\fix40\MessageCracker.h MessageCracker.xsl FIX40.xml
xsltproc -o ..\src\C++\fix41\MessageCracker.h MessageCracker.xsl FIX41.xml
xsltproc -o ..\src\C++\fix42\MessageCracker.h MessageCracker.xsl FIX42.xml
xsltproc -o ..\src\C++\fix43\MessageCracker.h MessageCracker.xsl FIX43.xml
xsltproc -o ..\src\C++\fix44\MessageCracker.h MessageCracker.xsl FIX44.xml
xsltproc -o ..\src\C++\fix50\MessageCracker.h MessageCracker.xsl FIX50.xml
xsltproc -o ..\src\C++\fixt11\MessageCracker.h MessageCracker.xsl FIXT11.xml