name: Build with Autotools
on: [pull_request, push]

jobs:
    build:
      runs-on: ${{ matrix.runner }}
      strategy:
          fail-fast: false
          matrix:
              runner: [ubuntu-latest, macos-latest]
              configuration: [Release]
              compiler-settings: ['']
              include:
                - runner: ubuntu-latest
                  compiler-settings: CXX=clang++ CC=clang
                - runner: macos-latest
                  compiler-settings: CXX=g++ CC=gcc
      steps:
      - name: Install dependencies
        uses: actions/setup-python@v5
        with:
            python-version: '3.10' 
            
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies for macOS
        if: matrix.runner == 'macos-latest'
        run: brew install autoconf automake libtool openssl

      - name: Link dependencies for macOS
        if: matrix.runner == 'macos-latest'
        run: brew link autoconf automake libtool openssl

      - name: Bootstrap
        shell: bash
        run: ./bootstrap

      - name: Configure ${{ matrix.compiler-settings }}
        shell: bash
        run: ${{ matrix.compiler-settings }} ./configure
        if: ${{ success() && matrix.compiler-settings != '' }}

      - name: Configure
        shell: bash
        run: CPPFLAGS=-I/opt/homebrew/opt/openssl/include LDFLAGS=-L/opt/homebrew/opt/openssl/lib ./configure --with-python3 --with-ruby --with-openssl
        if: ${{ success() && matrix.compiler-settings == '' }}

      - name: Make
        shell: bash
        run:  make

      - name: Make check
        shell: bash
        run: make check
