name: Build with CMake
on: [pull_request, push]

jobs:
    build:
      runs-on: ${{ matrix.runner }}
      strategy:
          matrix:
              runner: [windows-2019, ubuntu-latest, macos-latest]
              configuration: [Debug, Release]
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=$Configuration -DCMAKE_INSTALL_PREFIX=../install_prefix/$Configuration
        env:
          Configuration: ${{ matrix.configuration }}
      - name: Build
        shell: bash
        run: |
          cd build
          cmake --build . --config $Configuration
        env:
          Configuration: ${{ matrix.configuration }}
      - name: Install
        shell: bash
        run: |
          cd build
          cmake --install . --config $Configuration
        env:
          Configuration: ${{ matrix.configuration }}
