name: Build with Autotools
on: [pull_request, push]

jobs:
    build:
      runs-on: ${{ matrix.runner }}
      strategy:
          matrix:
              runner: [ubuntu-latest, macos-latest]
              configuration: [Release]
              include:
                - configuration: Release
                  config: release
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install autoconf and automake for macOS
        if: matrix.runner == 'macos-latest'
        run: brew install autoconf automake

      - name: Bootstrap
        shell: bash
        run: ./bootstrap

      - name: Configure
        shell: bash
        run: ./configure

      - name: Make
        shell: bash
        run:  make -j

      - name: Make check
        shell: bash
        run: make check

      - name: Cat test-suite.log
        if: ${{ always() }}
        shell: bash
        run: |
          test -f test/test-suite.log && cat test/test-suite.log
