name: Build with CMake
on: [pull_request, push]

jobs:
    build:
      runs-on: ${{ matrix.runner }}
      strategy:
          matrix:
              runner: [windows-2019, ubuntu-latest, macos-latest]
              configuration: [Debug, Release]
              include:
                - runner: windows-2019
                  solution: quickfix_vs15.sln
                  targetframeworkversion: v4.8
                  platformtoolset: v142
                  windowstargetplatformversion: 10.0
                - runner: windows-2019
                  platform: Win32
                  configuration: Release
                  copyheaders: true
      steps:
      - name: Checkout
        uses: actions/checkout@v2
